### ISSUE TITLE
UnicodeMath Version 3.2

### ISSUE THREAD

**Issue by MurrayIII** [doersino/UnicodeMathML#3]
https://www.unicode.org/notes/tn28/UTN28-PlainTextMath-v3.2.pdf is online and includes a new section on math color using the operators given in this site.

**Comment by MurrayIII** [comment]
In January, Igalia's MathML core was shipped in Chromium and is available in current versions of Chrome, Edge, and Opera.

**Comment by doersino** [comment]
I've added relevant notes to the `README.md`, thank you! (Better late than never... I'll reply to your emails later today.)

**Comment by MurrayIII** [comment]
Great! Check out my version of the Playground 😊 I’m hiking a mountain right now. Beautiful but tiring. Cheers!

Murray

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
